### ISSUE TITLE
Error with the file var\cache\dev/ztemp/pagelock.lock

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/PageLock#2]
ZK2.0.12 (upgraded, not fresh install)
Pagelock 1.2.3
News 1.2.1

I have tried edit a new with MUNews and I got the error `Warning: fopen(C:\xampp-old\htdocs\portal_upgrade\var\cache\dev/ztemp/pagelock.lock): failed to open stream: No such file or directory`
`in modules\zikula\pagelock-module\Api\LockingApi.php (line 262) `
The first problem is the character '\' vrs '/'. I have Windows localhost.

The second problem is the the file `var/cache/dev/ztemp/pagelock.lock` is not generated or not exist. I search the file and the directory `ztemp`dont exist.

Thanks

**Comment by Guite** [comment]
If `ztemp` exists lock file creation works.
Hence, closing in favour of https://github.com/zikula/core/issues/3966
